version: '3'
services:
  app:
    container_name: app
    image: pg47347/rpcw2022:1.0
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db  
    ports:
      - "27017:27017"
